version: '2'
version: '3.0'
services: 
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
       - "3307:3306"
  app: 
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    #Connect folder project
    volumes: 
      - ".:/app"
    ports: 
       - "3000:3000"
    #Connect to services db
    depends_on:
      - db
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
volumes:
  mysql-data:
    driver: local